### ISSUE TITLE
Exporting to An AppVar

### ISSUE THREAD

**Issue by acagliano** [elfprince13/TITokens#1]
So I am trying to find out about an API that I can use to parse an XML file into a string, and then write that string out to a TI AppVar. For instance, an XML file with the following:
`<virusDefs>
<virus>
<opcode>somecode</opcode>
<desc>this does stuff</desc>
</virus>
...
</virusDefs>`
should parse into the following string (where the opcode and desc nodes repeat per item):
`[MDYY] [sizeof_opcode] [opcode] [sizeof_desc] [desc]`
And be written out into a TI appvar. The MDYY should be a timestamp with 1-byte month and day and 2-byte year.

I am able to generate the string myself! That's not an issue. The final step... generating the AppVar... that's what I need help with. I was hoping to write this script in PHP.

**Comment by elfprince13** [comment]
You can use TITokens to turn an arbitrary text file into a `.bin`, using whatever tokenization rules you want (specified in the TokenIDE XML format). Once you have a `.bin` you can add the `.8xv` header however you want. I typically use wabbitsign to generate `.8xp`, but it would be pretty easy to modify it to support `.8xv`, since the formats are essentially the same.

**Comment by acagliano** [comment]
So, let me sum up..
1. Parse XML string into string and output to text file.
2. Use TITokens to convert to .bin.
3. Use wabbitsign to make a .8xv

**Comment by elfprince13** [comment]
Right, though Wabbitsign will probably need slight modifications to handle the difference in headers between 8xv and 8xp.

**Comment by acagliano** [comment]
I could also simply set up my suite on-calc such that *importing* a virus definitions file converts it from a program to an appvar, and just build it as a program :)
